version: '3'

services:
  reverse-proxy:
    image: nginx:1.23.1
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    networks:
      - proshop-net
    depends_on:
      - frontend-app
      - backend-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access.log:/etc/nginx/access.log
  frontend-app:
    image: taufiq14s/proshop-frontend:latest
    container_name: proshop-frontend-app
    stdin_open: true
    #Because we use reverse-proxy we don't mapping port to outside of the host, let the reverse proxy handle it
    # ports:
    #   - "8080:80"
    networks:
      - proshop-net
    env_file: ./.env

  backend-app:
    image: taufiq14s/proshop-backend:latest
    container_name: proshop-backend-app
    #Because we use reverse-proxy we don't mapping port to outside of the host, let the reverse proxy handle it
    # ports:
    #   - "5000:5000"
    networks:
      - proshop-net
    depends_on:
      - mongodb
    env_file: ./.env

  mongodb:
    image: mongo:4.4.11
    container_name: proshop-mongodb-srv
    volumes:
        - ./proshop-app-data:/data/db
    #Enable port if you need to connect the mongodb
    # ports:
    #   - "27017:27017"
    networks:
      - proshop-net

networks:
  proshop-net:
    driver: bridge